apiVersion: apps/v1
kind: Deployment
metadata:
  name: recognition-model-deployment
  labels:
    app: f1-platform
    component: fastapi-recognize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recognition-model-app
  template:
    metadata:
      labels:
        app: recognition-model-app
    spec:
      containers:
        - name: recognition-model-app
          image: docker.io/azawalich/formula-1-fullstack-mlops:f1-recognition-model-v0.7
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10 
          env:
          - name: MINIO_URL
            value: minio.f1-platform.zawalich.pl
          - name: DEBUGGING_LOCAL
            value: "False"
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-dashboard-secret
                key: access_key
          - name: MINIO_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-dashboard-secret
                key: secret_key
          command: ["python", "-m", "main.py"]
          args: ["--minio-url", "$(MINIO_URL)", "--access-key", "$(MINIO_ACCESS_KEY)", "--secret-key", "$(MINIO_SECRET_ACCESS_KEY)", "--debugging-local", "$(DEBUGGING_LOCAL)"]