apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: recognition-model-ingress
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/ingress.class: "nginx"
    labels:
      app: f1-platform
      component: fastapi-recognize
spec:
  tls:
    - hosts:
      - recognize.f1-platform.zawalich.pl
      secretName: echo-tls
  rules:
    - host: recognize.f1-platform.zawalich.pl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: recognition-model-service
                port:
                  number: 8000